"""migrate chatbot and clean_blue to db and add global_ignore table

Revision ID: 36fda794cb68
Revises: 
Create Date: 2026-06-12 08:21:39.420088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36fda794cb68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_ignores',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Telegram user_id to ignore globally.'),
    sa.Column('reason', sa.String(length=256), nullable=True, comment='Reason for ignoring the user.'),
    sa.Column('ignored_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('chat_feature_settings', sa.Column('chatbot_enabled', sa.Boolean(), nullable=False, comment='Toggle for the AI chatbot auto-response subsystem.'))
    op.add_column('chat_feature_settings', sa.Column('clean_blue_enabled', sa.Boolean(), nullable=False, comment='Toggle for auto-deleting unknown bot command messages (bluetext).'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_feature_settings', 'clean_blue_enabled')
    op.drop_column('chat_feature_settings', 'chatbot_enabled')
    op.drop_table('global_ignores')
    # ### end Alembic commands ###
